version: '3.5'
services:
  analytic_api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - ugc
    ports:
      - 8000:8000

networks:
  ugc:
    external: true
